(() => {
  "use strict";

  const shared = {
    typeKeys: {
      "Звезда":"star", "Планета":"planet", "НАБЛЮДЕНИЕ":"observation", "ОТКРЫТИЕ":"discovery",
      "МИССИЯ":"mission", "ГЕОЛОГИЯ":"geology", "ЭКСПЕДИЦИЯ":"expedition", "АТМОСФЕРА":"atmosphere",
      "СОБЫТИЕ":"event", "МИССИЯ CURIOSITY":"missionCuriosity", "МИССИЯ PERSEVERANCE":"missionPerseverance",
      "АППАРАТ":"spacecraft", "ЕСТЕСТВЕННЫЙ СПУТНИК":"naturalSatellite", "ОРБИТАЛЬНАЯ СТАНЦИЯ":"orbitalStation",
      "ТЕЛЕСКОП":"telescope", "ГАЛИЛЕЕВ СПУТНИК":"galileanMoon"
    },
    orbiterNames: {
      earth:["Moon","ISS","Hubble"], mars:["Phobos","Deimos","MRO"],
      jupiter:["Io","Europa","Ganymede","Callisto","Juno"], saturn:["Enceladus","Rhea","Titan","Cassini"],
      uranus:["Miranda","Ariel","Titania","Oberon"], neptune:["Proteus","Triton","Nereid"]
    }
  };

  const ru = {
    code:"ru-RU", label:"RU", ui:{
      pageTitle:"Гелиос — интерактивная Солнечная система", brandSubtitle:"Солнечная система · живая карта",
      mapMode:"Режим карты", modeOrbit:"Орбиты", modeLineup:"По порядку", wallpaperMode:"РЕЖИМ ОБОЕВ",
      hideUi:"Скрыть служебный интерфейс", realtime:"РЕАЛЬНОЕ ВРЕМЯ", modeltime:"МОДЕЛЬНОЕ ВРЕМЯ", calculatedTime:"РАСЧЁТ НА МОМЕНТ",
      previousDay:"Предыдущий день", nextDay:"Следующий день", epoch:"ЭПОХА НАБЛЮДЕНИЯ", now:"Сейчас", startTime:"Запустить ход времени", speed:"СКОРОСТЬ",
      scaleTitle:"МАСШТАБ ПРОСТРАНСТВА", scenic:"Сжатый", relative:"По а.е.", scenicNote:"Орбиты сжаты нелинейно, чтобы все планеты оставались видны.", relativeNote:"Масштаб основан на а.е.; внутренняя область слегка расширена, чтобы планеты не сливались с Солнцем.",
      ecliptic:"Эклиптика J2000", calculated:"Положения вычислены", hintOrbit:"<span>ЛКМ</span> вращать <span>КЛИК</span> исследовать", hintOrbitLocked:"<span>КЛИК</span> исследовать", hintOrbitNoExplore:"<span>ЛКМ</span> вращать <span>ПЕРЕХОДЫ ОТКЛЮЧЕНЫ</span>", hintLockedNoExplore:"<span>ПЕРЕХОДЫ ОТКЛЮЧЕНЫ</span>", hintLineup:"<span>ФИКСИРОВАННЫЙ РАЗРЕЗ</span> · <span>КЛИК</span> исследовать объект", hintLineupNoExplore:"<span>ФИКСИРОВАННЫЙ РАЗРЕЗ</span> · <span>ПЕРЕХОДЫ ОТКЛЮЧЕНЫ</span>", rotationOn:"ВРАЩЕНИЕ: ВКЛ", rotationOff:"ВРАЩЕНИЕ: ВЫКЛ", rotationToggle:"Включить или отключить вращение левой кнопкой мыши", rotationDisabled:"ВРАЩЕНИЕ ЛКМ ОТКЛЮЧЕНО", explorationOn:"ПЕРЕХОДЫ: ВКЛ", explorationOff:"ПЕРЕХОДЫ: ВЫКЛ", explorationToggle:"Разрешить или запретить открытие планет и Солнца по клику",
      showUi:"ПОКАЗАТЬ ИНТЕРФЕЙС", desktopItems:"Элементы рабочего стола", waitingAudio:"ОЖИДАНИЕ WE", audioLive:"АУДИО · LIVE", noSignal:"НЕТ СИГНАЛА", apiUnavailable:"API НЕДОСТУПЕН",
      timer:"ТАЙМЕР", ready:"ГОТОВ", done:"ГОТОВО", running:"ИДЁТ", pause:"ПАУЗА", again:"СНОВА", start:"СТАРТ", reset:"СБРОС",
      back:"← К карте", backAria:"Вернуться к карте", facts:"Коротко о главном", discoveries:"Точки исследования", companions:"Спутники и аппараты", orbitNote:"Орбиты показаны схематично и сжаты для режима исследования.",
      dragPlanet:"ТЯНИТЕ ПЛАНЕТУ, ЧТОБЫ ВРАЩАТЬ", previousObject:"Предыдущий объект", nextObject:"Следующий объект", close:"Закрыть", loading:"СТРОИМ ОРБИТЫ", ephemerides:"Эфемериды · J2000",
      object:"ОБЪЕКТ", center:"центр системы", centerShort:"ЦЕНТР", au:"а.е.", dossier:"открыть досье", schematicPoint:"СХЕМАТИЧЕСКАЯ ТОЧКА", dynamicLongitude:"ДИНАМИЧЕСКАЯ ДОЛГОТА",
      north:"С. Ш.", south:"Ю. Ш.", east:"В. Д.", west:"З. Д.", craftShort:"КА", archive:"АРХИВ", orbit:"ОРБИТА", day:"ДЕНЬ", realSpeed:"1× реал", stopped:"стоп", daysPerSecond:"дн/с",
      language:"Язык", spectrum:"СПЕКТР", wave:"ВОЛНА", radial:"РАДИАЛ", mirror:"ЗЕРКАЛО", rings:"КОЛЬЦА", constellation:"СОЗВЕЗДИЕ",
      hotspotGeneric:"Научная отметка «{name}». Координаты привязаны к вращающейся поверхности объекта.", moonGeneric:"{name} — спутник на орбите исследуемого небесного тела.", craftGeneric:"{name} — научный аппарат или станция, связанная с исследованием этого объекта."
    }, types:{star:"Звезда",planet:"Планета",observation:"НАБЛЮДЕНИЕ",discovery:"ОТКРЫТИЕ",mission:"МИССИЯ",geology:"ГЕОЛОГИЯ",expedition:"ЭКСПЕДИЦИЯ",atmosphere:"АТМОСФЕРА",event:"СОБЫТИЕ",missionCuriosity:"МИССИЯ CURIOSITY",missionPerseverance:"МИССИЯ PERSEVERANCE",spacecraft:"АППАРАТ",naturalSatellite:"ЕСТЕСТВЕННЫЙ СПУТНИК",orbitalStation:"ОРБИТАЛЬНАЯ СТАНЦИЯ",telescope:"ТЕЛЕСКОП",galileanMoon:"ГАЛИЛЕЕВ СПУТНИК"}
  };

  const en = {
    code:"en-US", label:"EN", ui:{
      pageTitle:"Helios — Interactive Solar System", brandSubtitle:"Solar System · live map", mapMode:"Map mode", modeOrbit:"Orbits", modeLineup:"In order", wallpaperMode:"WALLPAPER MODE", hideUi:"Hide interface",
      realtime:"REAL TIME", modeltime:"SIMULATED TIME", calculatedTime:"CALCULATED MOMENT", previousDay:"Previous day", nextDay:"Next day", epoch:"OBSERVATION EPOCH", now:"Now", startTime:"Start time", speed:"SPEED",
      scaleTitle:"SPACE SCALE", scenic:"Compressed", relative:"By AU", scenicNote:"Orbits are compressed non-linearly so every planet remains visible.", relativeNote:"The scale is based on AU; the inner region is slightly expanded to keep planets separate from the Sun.",
      ecliptic:"J2000 ecliptic", calculated:"Positions calculated", hintOrbit:"<span>LMB</span> rotate <span>CLICK</span> explore", hintOrbitLocked:"<span>CLICK</span> explore", hintOrbitNoExplore:"<span>LMB</span> rotate <span>PLANET OPENING DISABLED</span>", hintLockedNoExplore:"<span>PLANET OPENING DISABLED</span>", hintLineup:"<span>FIXED SECTION</span> · <span>CLICK</span> to explore", hintLineupNoExplore:"<span>FIXED SECTION</span> · <span>PLANET OPENING DISABLED</span>", rotationOn:"ROTATION: ON", rotationOff:"ROTATION: OFF", rotationToggle:"Enable or disable left-mouse rotation", rotationDisabled:"LMB ROTATION DISABLED", explorationOn:"PLANETS: OPEN", explorationOff:"PLANETS: LOCKED", explorationToggle:"Allow or block opening planets and the Sun on click",
      showUi:"SHOW INTERFACE", desktopItems:"Desktop elements", waitingAudio:"WAITING FOR WE", audioLive:"AUDIO · LIVE", noSignal:"NO SIGNAL", apiUnavailable:"API UNAVAILABLE",
      timer:"TIMER", ready:"READY", done:"DONE", running:"RUNNING", pause:"PAUSE", again:"AGAIN", start:"START", reset:"RESET", back:"← Back to map", backAria:"Return to map",
      facts:"In brief", discoveries:"Research points", companions:"Moons and spacecraft", orbitNote:"Orbits are schematic and compressed for exploration mode.", dragPlanet:"DRAG THE PLANET TO ROTATE",
      previousObject:"Previous object", nextObject:"Next object", close:"Close", loading:"BUILDING ORBITS", ephemerides:"Ephemerides · J2000", object:"OBJECT", center:"system center", centerShort:"CENTER", au:"AU", dossier:"open dossier",
      schematicPoint:"SCHEMATIC POINT", dynamicLongitude:"DYNAMIC LONGITUDE", north:"N", south:"S", east:"E", west:"W", craftShort:"SC", archive:"ARCHIVE", orbit:"ORBIT", day:"DAY", realSpeed:"1× real", stopped:"stopped", daysPerSecond:"days/s",
      language:"Language", spectrum:"SPECTRUM", wave:"WAVE", radial:"RADIAL", mirror:"MIRROR", rings:"RINGS", constellation:"CONSTELLATION",
      hotspotGeneric:"Scientific marker “{name}”. Its coordinates follow the rotating surface.", moonGeneric:"{name} is a moon orbiting the selected celestial body.", craftGeneric:"{name} is a scientific spacecraft or station associated with this body."
    }, types:{star:"Star",planet:"Planet",observation:"OBSERVATION",discovery:"DISCOVERY",mission:"MISSION",geology:"GEOLOGY",expedition:"EXPEDITION",atmosphere:"ATMOSPHERE",event:"EVENT",missionCuriosity:"CURIOSITY MISSION",missionPerseverance:"PERSEVERANCE MISSION",spacecraft:"SPACECRAFT",naturalSatellite:"NATURAL SATELLITE",orbitalStation:"ORBITAL STATION",telescope:"TELESCOPE",galileanMoon:"GALILEAN MOON"},
    bodies:{
      sun:{name:"Sun",latin:"SOL · G2V CLASS STAR",lead:"The heart of our system: a nearly perfect sphere of hot plasma whose gravity holds the planets and whose light powers them.",story:"About 600 million tonnes of hydrogen undergo fusion in the core every second. Light takes tens of thousands of years to reach the surface, then only 8 minutes 20 seconds to reach Earth.",stats:[["Diameter","1,392,700 km"],["System mass","99.86%"],["Temperature","5,772 K"],["Age","4.57 billion years"]],hotspots:["Galileo’s sunspots","Helioseismology","Parker Solar Probe"]},
      mercury:{name:"Mercury",latin:"MERCURIUS · ROCKY PLANET",lead:"The closest and fastest planet: one Mercurian year lasts only 88 Earth days.",story:"Mercury has almost no atmosphere, so its surface experiences extreme temperature swings. Water ice survives in permanently shadowed polar craters.",stats:[["Diameter","4,879 km"],["Year","87.97 days"],["Day","58.6 days"],["Moons","0"]],hotspots:["Caloris Planitia","Ice in Prokofiev crater","MESSENGER finale"]},
      venus:{name:"Venus",latin:"VENUS · ROCKY PLANET",lead:"An Earth-sized world hidden beneath sulfuric-acid clouds and the strongest greenhouse effect in the Solar System.",story:"Surface pressure is 92 times Earth’s and the temperature can melt lead. Venus rotates backwards, and its solar day is longer than its year.",stats:[["Diameter","12,104 km"],["Year","224.7 days"],["Temperature","+464 °C"],["Pressure","92 atm"]],hotspots:["Venera 7 landing","Maxwell Montes","Maat Mons"]},
      earth:{name:"Earth",latin:"TERRA · OCEAN PLANET",lead:"The only known world with stable surface water, an oxygen-rich atmosphere and life.",story:"Plate tectonics renews the surface, the magnetic field shields the atmosphere, and the large Moon stabilizes Earth’s tilt. Together they create rare conditions for a complex biosphere.",stats:[["Diameter","12,742 km"],["Year","365.256 days"],["Water","71% of surface"],["Moons","1"]],hotspots:["Lake Vostok beneath the ice","Mariana Trench","Chicxulub crater"]},
      mars:{name:"Mars",latin:"MARS · RED PLANET",lead:"A cold desert of ancient riverbeds, giant volcanoes and the best archive of past habitability beyond Earth.",story:"Rivers and lakes once existed on Mars. Today most water is ice and the thin carbon-dioxide atmosphere retains little heat. Orbiters and rovers search for evidence of past climate and ancient life.",stats:[["Diameter","6,779 km"],["Year","686.98 days"],["Day","24 h 39 min"],["Moons","2"]],hotspots:["Gale crater","Jezero crater","Olympus Mons"]},
      jupiter:{name:"Jupiter",latin:"IUPPITER · GAS GIANT",lead:"The largest planet: a world without a solid surface whose gravity governs an entire family of moons.",story:"Jupiter is more than twice as massive as all other planets combined. Deep pressure turns hydrogen metallic and drives the strongest planetary magnetic field.",stats:[["Diameter","139,820 km"],["Year","11.86 years"],["Day","9 h 56 min"],["Known moons","95+"]],hotspots:["Great Red Spot","Shoemaker–Levy 9 impact","Juno polar cyclones"]},
      saturn:{name:"Saturn",latin:"SATURNUS · RINGED GIANT",lead:"A gas giant with a vast system of thin, intricate and constantly changing ice rings.",story:"Saturn’s rings span hundreds of thousands of kilometres, yet their main layer is thinner than a skyscraper. Moon gravity and ice-particle resonances create thousands of bands and waves.",stats:[["Diameter","116,460 km"],["Year","29.45 years"],["Density","0.687 g/cm³"],["Known moons","140+"]],hotspots:["North polar hexagon","Great White Storm","Cassini finale"]},
      uranus:{name:"Uranus",latin:"URANUS · ICE GIANT",lead:"An ice giant tipped on its side, with its poles alternately facing almost directly toward the Sun.",story:"Its unusual tilt probably followed an ancient giant impact. Beneath the calm blue atmosphere lies a high-pressure mantle rich in water, ammonia and methane.",stats:[["Diameter","50,724 km"],["Year","84.0 years"],["Axial tilt","97.77°"],["Known moons","27+"]],hotspots:["Voyager 2 flyby","Offset magnetic field","Polar warming"]},
      neptune:{name:"Neptune",latin:"NEPTUNUS · ICE GIANT",lead:"The farthest major planet: a dark, cold world with the fastest winds in the Solar System.",story:"Neptune was predicted mathematically before it was observed. Methane absorbs red light, while another haze component may intensify its deep blue colour.",stats:[["Diameter","49,244 km"],["Year","164.8 years"],["Winds","up to 2,100 km/h"],["Known moons","14+"]],hotspots:["Great Dark Spot","Scooter clouds","Voyager 2 flyby"]}
    }
  };

  const de = {
    code:"de-DE", label:"DE", ui:{
      pageTitle:"Helios — Interaktives Sonnensystem",brandSubtitle:"Sonnensystem · Live-Karte",mapMode:"Kartenmodus",modeOrbit:"Umlaufbahnen",modeLineup:"Reihenfolge",wallpaperMode:"HINTERGRUNDMODUS",hideUi:"Bedienoberfläche ausblenden",realtime:"ECHTZEIT",modeltime:"SIMULIERTE ZEIT",calculatedTime:"BERECHNETER ZEITPUNKT",previousDay:"Vorheriger Tag",nextDay:"Nächster Tag",epoch:"BEOBACHTUNGSZEIT",now:"Jetzt",startTime:"Zeit starten",speed:"GESCHWINDIGKEIT",scaleTitle:"RAUMMASSSTAB",scenic:"Komprimiert",relative:"Nach AE",scenicNote:"Die Bahnen sind nichtlinear komprimiert, damit alle Planeten sichtbar bleiben.",relativeNote:"Entfernungen folgen astronomischen Einheiten; Planetengrößen sind vergrößert.",ecliptic:"J2000-Ekliptik",calculated:"Positionen berechnet",hintOrbit:"<span>LMT</span> drehen <span>RAD</span> zoomen <span>KLICK</span> erkunden",hintLineup:"<span>FESTER SCHNITT</span> · <span>KLICK</span> zum Erkunden",showUi:"OBERFLÄCHE ZEIGEN",desktopItems:"Desktop-Elemente",waitingAudio:"WARTE AUF WE",audioLive:"AUDIO · LIVE",noSignal:"KEIN SIGNAL",apiUnavailable:"API NICHT VERFÜGBAR",timer:"TIMER",ready:"BEREIT",done:"FERTIG",running:"LÄUFT",pause:"PAUSE",again:"NEU",start:"START",reset:"ZURÜCK",back:"← Zur Karte",backAria:"Zur Karte zurückkehren",facts:"Kurz erklärt",discoveries:"Forschungspunkte",companions:"Monde und Raumfahrzeuge",orbitNote:"Bahnen sind für den Forschungsmodus schematisch und komprimiert.",dragPlanet:"PLANET ZUM DREHEN ZIEHEN",previousObject:"Vorheriges Objekt",nextObject:"Nächstes Objekt",close:"Schließen",loading:"BAHNEN WERDEN ERSTELLT",ephemerides:"Ephemeriden · J2000",object:"OBJEKT",center:"Systemzentrum",centerShort:"ZENTRUM",au:"AE",dossier:"Dossier öffnen",schematicPoint:"SCHEMATISCHER PUNKT",dynamicLongitude:"DYNAMISCHE LÄNGE",north:"N",south:"S",east:"O",west:"W",craftShort:"RF",archive:"ARCHIV",orbit:"UMLAUFBAHN",day:"TAG",realSpeed:"1× real",stopped:"Stopp",daysPerSecond:"Tage/s",language:"Sprache",spectrum:"SPEKTRUM",wave:"WELLE",radial:"RADIAL",mirror:"SPIEGEL",rings:"RINGE",constellation:"STERNBILD",hotspotGeneric:"Wissenschaftliche Markierung „{name}“. Die Koordinaten folgen der rotierenden Oberfläche.",moonGeneric:"{name} ist ein Mond auf einer Umlaufbahn um den ausgewählten Himmelskörper.",craftGeneric:"{name} ist ein wissenschaftliches Raumfahrzeug oder eine Station zur Erforschung dieses Körpers."
    },types:{star:"Stern",planet:"Planet",observation:"BEOBACHTUNG",discovery:"ENTDECKUNG",mission:"MISSION",geology:"GEOLOGIE",expedition:"EXPEDITION",atmosphere:"ATMOSPHÄRE",event:"EREIGNIS",missionCuriosity:"CURIOSITY-MISSION",missionPerseverance:"PERSEVERANCE-MISSION",spacecraft:"RAUMFAHRZEUG",naturalSatellite:"NATÜRLICHER SATELLIT",orbitalStation:"ORBITALSTATION",telescope:"TELESKOP",galileanMoon:"GALILEISCHER MOND"},
    bodies:{
      sun:{name:"Sonne",latin:"SOL · STERN DER KLASSE G2V",lead:"Das Herz unseres Systems: eine fast perfekte Kugel aus heißem Plasma, deren Gravitation die Planeten bindet und deren Licht sie versorgt.",story:"Im Kern verschmelzen jede Sekunde rund 600 Millionen Tonnen Wasserstoff. Das Licht braucht Zehntausende Jahre bis zur Oberfläche und nur 8 Minuten 20 Sekunden bis zur Erde.",stats:[["Durchmesser","1.392.700 km"],["Systemmasse","99,86 %"],["Temperatur","5.772 K"],["Alter","4,57 Mrd. Jahre"]],hotspots:["Galileis Sonnenflecken","Helioseismologie","Parker Solar Probe"]},
      mercury:{name:"Merkur",latin:"MERCURIUS · GESTEINSPLANET",lead:"Der sonnennächste und schnellste Planet; ein Merkurjahr dauert nur 88 Erdtage.",story:"Merkur besitzt kaum Atmosphäre und erlebt extreme Temperaturschwankungen. In dauerhaft verschatteten Polkratern befindet sich Wassereis.",stats:[["Durchmesser","4.879 km"],["Jahr","87,97 Tage"],["Tag","58,6 Tage"],["Monde","0"]],hotspots:["Caloris Planitia","Eis im Krater Prokofiev","Ende von MESSENGER"]},
      venus:{name:"Venus",latin:"VENUS · GESTEINSPLANET",lead:"Eine erdgroße Welt unter Schwefelsäurewolken mit dem stärksten Treibhauseffekt des Sonnensystems.",story:"Der Bodendruck beträgt das 92-Fache der Erde, die Hitze schmilzt Blei. Venus rotiert rückwärts; ihr Sonnentag ist länger als ihr Jahr.",stats:[["Durchmesser","12.104 km"],["Jahr","224,7 Tage"],["Temperatur","+464 °C"],["Druck","92 atm"]],hotspots:["Landung von Venera 7","Maxwell Montes","Maat Mons"]},
      earth:{name:"Erde",latin:"TERRA · OZEANPLANET",lead:"Die einzige bekannte Welt mit dauerhaftem Oberflächenwasser, Sauerstoffatmosphäre und Leben.",story:"Plattentektonik erneuert die Oberfläche, das Magnetfeld schützt die Atmosphäre und der große Mond stabilisiert die Erdachse. So entstehen seltene Bedingungen für eine komplexe Biosphäre.",stats:[["Durchmesser","12.742 km"],["Jahr","365,256 Tage"],["Wasser","71 % der Oberfläche"],["Monde","1"]],hotspots:["Wostoksee unter dem Eis","Marianengraben","Chicxulub-Krater"]},
      mars:{name:"Mars",latin:"MARS · ROTER PLANET",lead:"Eine kalte Wüste mit alten Flussbetten, riesigen Vulkanen und einem einzigartigen Archiv früherer Bewohnbarkeit.",story:"Einst gab es Flüsse und Seen. Heute steckt Wasser meist im Eis, während die dünne CO₂-Atmosphäre kaum Wärme hält. Sonden und Rover suchen Spuren des alten Klimas und Lebens.",stats:[["Durchmesser","6.779 km"],["Jahr","686,98 Tage"],["Tag","24 h 39 min"],["Monde","2"]],hotspots:["Gale-Krater","Jezero-Krater","Olympus Mons"]},
      jupiter:{name:"Jupiter",latin:"IUPPITER · GASRIESE",lead:"Der größte Planet: eine Welt ohne feste Oberfläche, deren Gravitation eine ganze Mondfamilie beherrscht.",story:"Jupiter ist mehr als doppelt so massereich wie alle anderen Planeten zusammen. Tiefer Druck macht Wasserstoff metallisch und erzeugt ein gewaltiges Magnetfeld.",stats:[["Durchmesser","139.820 km"],["Jahr","11,86 Jahre"],["Tag","9 h 56 min"],["Bekannte Monde","95+"]],hotspots:["Großer Roter Fleck","Einschlag Shoemaker–Levy 9","Polare Wirbel von Juno"]},
      saturn:{name:"Saturn",latin:"SATURNUS · RINGRIESE",lead:"Ein Gasriese mit einem riesigen, dünnen und ständig veränderlichen System aus Eisringen.",story:"Saturns Ringe reichen Hunderttausende Kilometer weit, sind aber überwiegend dünner als ein Wolkenkratzer. Mondgravitation und Resonanzen formen zahllose Bänder und Wellen.",stats:[["Durchmesser","116.460 km"],["Jahr","29,45 Jahre"],["Dichte","0,687 g/cm³"],["Bekannte Monde","140+"]],hotspots:["Nördliches Hexagon","Großer Weißer Sturm","Ende von Cassini"]},
      uranus:{name:"Uranus",latin:"URANUS · EISRIESE",lead:"Ein auf die Seite gekippter Eisriese, dessen Pole abwechselnd fast direkt zur Sonne zeigen.",story:"Die ungewöhnliche Neigung entstand vermutlich durch einen uralten Großaufprall. Unter der ruhigen blauen Atmosphäre liegt ein Hochdruckmantel aus Wasser, Ammoniak und Methan.",stats:[["Durchmesser","50.724 km"],["Jahr","84,0 Jahre"],["Achsenneigung","97,77°"],["Bekannte Monde","27+"]],hotspots:["Vorbeiflug von Voyager 2","Versetztes Magnetfeld","Polare Erwärmung"]},
      neptune:{name:"Neptun",latin:"NEPTUNUS · EISRIESE",lead:"Der fernste große Planet: eine dunkle, kalte Welt mit den schnellsten Winden im Sonnensystem.",story:"Neptun wurde mathematisch vorhergesagt, bevor man ihn sah. Methan absorbiert rotes Licht; ein weiterer Dunstbestandteil könnte das tiefe Blau verstärken.",stats:[["Durchmesser","49.244 km"],["Jahr","164,8 Jahre"],["Winde","bis 2.100 km/h"],["Bekannte Monde","14+"]],hotspots:["Großer Dunkler Fleck","Scooter-Wolken","Vorbeiflug von Voyager 2"]}
    }
  };

  const es = {
    code:"es-ES",label:"ES",ui:{
      pageTitle:"Helios — Sistema Solar interactivo",brandSubtitle:"Sistema Solar · mapa en vivo",mapMode:"Modo del mapa",modeOrbit:"Órbitas",modeLineup:"En orden",wallpaperMode:"MODO FONDO",hideUi:"Ocultar interfaz",realtime:"TIEMPO REAL",modeltime:"TIEMPO SIMULADO",calculatedTime:"MOMENTO CALCULADO",previousDay:"Día anterior",nextDay:"Día siguiente",epoch:"ÉPOCA DE OBSERVACIÓN",now:"Ahora",startTime:"Iniciar tiempo",speed:"VELOCIDAD",scaleTitle:"ESCALA ESPACIAL",scenic:"Comprimida",relative:"Por UA",scenicNote:"Las órbitas se comprimen de forma no lineal para mantener visibles todos los planetas.",relativeNote:"Las distancias siguen unidades astronómicas; los tamaños planetarios están ampliados.",ecliptic:"Eclíptica J2000",calculated:"Posiciones calculadas",hintOrbit:"<span>BOTÓN IZQ.</span> girar <span>RUEDA</span> zoom <span>CLIC</span> explorar",hintLineup:"<span>CORTE FIJO</span> · <span>CLIC</span> para explorar",showUi:"MOSTRAR INTERFAZ",desktopItems:"Elementos de escritorio",waitingAudio:"ESPERANDO WE",audioLive:"AUDIO · EN VIVO",noSignal:"SIN SEÑAL",apiUnavailable:"API NO DISPONIBLE",timer:"TEMPORIZADOR",ready:"LISTO",done:"TERMINADO",running:"ACTIVO",pause:"PAUSA",again:"DE NUEVO",start:"INICIAR",reset:"REINICIAR",back:"← Volver al mapa",backAria:"Volver al mapa",facts:"En resumen",discoveries:"Puntos de investigación",companions:"Lunas y naves",orbitNote:"Las órbitas son esquemáticas y están comprimidas para el modo de exploración.",dragPlanet:"ARRASTRA EL PLANETA PARA GIRARLO",previousObject:"Objeto anterior",nextObject:"Objeto siguiente",close:"Cerrar",loading:"CONSTRUYENDO ÓRBITAS",ephemerides:"Efemérides · J2000",object:"OBJETO",center:"centro del sistema",centerShort:"CENTRO",au:"UA",dossier:"abrir informe",schematicPoint:"PUNTO ESQUEMÁTICO",dynamicLongitude:"LONGITUD DINÁMICA",north:"N",south:"S",east:"E",west:"O",craftShort:"NV",archive:"ARCHIVO",orbit:"ÓRBITA",day:"DÍA",realSpeed:"1× real",stopped:"detenido",daysPerSecond:"días/s",language:"Idioma",spectrum:"ESPECTRO",wave:"ONDA",radial:"RADIAL",mirror:"ESPEJO",rings:"ANILLOS",constellation:"CONSTELACIÓN",hotspotGeneric:"Marcador científico «{name}». Sus coordenadas siguen la superficie en rotación.",moonGeneric:"{name} es una luna en órbita alrededor del cuerpo celeste seleccionado.",craftGeneric:"{name} es una nave o estación científica asociada con la exploración de este cuerpo."
    },types:{star:"Estrella",planet:"Planeta",observation:"OBSERVACIÓN",discovery:"DESCUBRIMIENTO",mission:"MISIÓN",geology:"GEOLOGÍA",expedition:"EXPEDICIÓN",atmosphere:"ATMÓSFERA",event:"EVENTO",missionCuriosity:"MISIÓN CURIOSITY",missionPerseverance:"MISIÓN PERSEVERANCE",spacecraft:"NAVE ESPACIAL",naturalSatellite:"SATÉLITE NATURAL",orbitalStation:"ESTACIÓN ORBITAL",telescope:"TELESCOPIO",galileanMoon:"LUNA GALILEANA"},
    bodies:{
      sun:{name:"Sol",latin:"SOL · ESTRELLA DE CLASE G2V",lead:"El corazón del sistema: una esfera casi perfecta de plasma caliente cuya gravedad retiene los planetas y cuya luz los alimenta.",story:"Unos 600 millones de toneladas de hidrógeno se fusionan en el núcleo cada segundo. La luz tarda decenas de miles de años en salir y solo 8 minutos 20 segundos en llegar a la Tierra.",stats:[["Diámetro","1 392 700 km"],["Masa del sistema","99,86 %"],["Temperatura","5 772 K"],["Edad","4,57 mil millones de años"]],hotspots:["Manchas solares de Galileo","Heliosismología","Parker Solar Probe"]},
      mercury:{name:"Mercurio",latin:"MERCURIUS · PLANETA ROCOSO",lead:"El planeta más cercano al Sol y el más rápido: su año dura solo 88 días terrestres.",story:"Mercurio casi no tiene atmósfera y sufre cambios extremos de temperatura. En los cráteres polares siempre en sombra sobrevive hielo de agua.",stats:[["Diámetro","4 879 km"],["Año","87,97 días"],["Día","58,6 días"],["Lunas","0"]],hotspots:["Caloris Planitia","Hielo en el cráter Prokofiev","Final de MESSENGER"]},
      venus:{name:"Venus",latin:"VENUS · PLANETA ROCOSO",lead:"Un mundo del tamaño de la Tierra oculto por nubes de ácido sulfúrico y el mayor efecto invernadero del Sistema Solar.",story:"La presión superficial es 92 veces la terrestre y la temperatura derrite plomo. Venus gira al revés y su día solar es más largo que su año.",stats:[["Diámetro","12 104 km"],["Año","224,7 días"],["Temperatura","+464 °C"],["Presión","92 atm"]],hotspots:["Aterrizaje de Venera 7","Maxwell Montes","Maat Mons"]},
      earth:{name:"Tierra",latin:"TERRA · PLANETA OCEÁNICO",lead:"El único mundo conocido con agua superficial estable, atmósfera de oxígeno y vida.",story:"La tectónica renueva la superficie, el campo magnético protege la atmósfera y la gran Luna estabiliza la inclinación. Todo ello crea condiciones excepcionales para una biosfera compleja.",stats:[["Diámetro","12 742 km"],["Año","365,256 días"],["Agua","71 % de la superficie"],["Lunas","1"]],hotspots:["Lago Vostok bajo el hielo","Fosa de las Marianas","Cráter Chicxulub"]},
      mars:{name:"Marte",latin:"MARS · PLANETA ROJO",lead:"Un desierto frío con antiguos cauces, volcanes gigantes y el mejor archivo de habitabilidad pasada fuera de la Tierra.",story:"Marte tuvo ríos y lagos. Hoy el agua es principalmente hielo y la fina atmósfera de CO₂ conserva poco calor. Orbitadores y róveres buscan señales del clima antiguo y de posible vida.",stats:[["Diámetro","6 779 km"],["Año","686,98 días"],["Día","24 h 39 min"],["Lunas","2"]],hotspots:["Cráter Gale","Cráter Jezero","Monte Olimpo"]},
      jupiter:{name:"Júpiter",latin:"IUPPITER · GIGANTE GASEOSO",lead:"El planeta más grande: un mundo sin superficie sólida cuya gravedad gobierna toda una familia de lunas.",story:"Júpiter tiene más del doble de masa que todos los demás planetas juntos. La presión vuelve metálico el hidrógeno y genera un enorme campo magnético.",stats:[["Diámetro","139 820 km"],["Año","11,86 años"],["Día","9 h 56 min"],["Lunas conocidas","95+"]],hotspots:["Gran Mancha Roja","Impacto Shoemaker–Levy 9","Ciclones polares de Juno"]},
      saturn:{name:"Saturno",latin:"SATURNUS · GIGANTE ANILLADO",lead:"Un gigante gaseoso con un vasto sistema de anillos de hielo, fino, complejo y cambiante.",story:"Los anillos se extienden cientos de miles de kilómetros, pero su capa principal es más delgada que un rascacielos. La gravedad de las lunas y las resonancias crean miles de bandas y ondas.",stats:[["Diámetro","116 460 km"],["Año","29,45 años"],["Densidad","0,687 g/cm³"],["Lunas conocidas","140+"]],hotspots:["Hexágono del polo norte","Gran Tormenta Blanca","Final de Cassini"]},
      uranus:{name:"Urano",latin:"URANUS · GIGANTE HELADO",lead:"Un gigante helado inclinado de lado, cuyos polos miran alternativamente casi de frente al Sol.",story:"Su inclinación probablemente procede de un impacto gigante antiguo. Bajo la tranquila atmósfera azul hay un manto de agua, amoníaco y metano a enormes presiones.",stats:[["Diámetro","50 724 km"],["Año","84,0 años"],["Inclinación axial","97,77°"],["Lunas conocidas","27+"]],hotspots:["Sobrevuelo de Voyager 2","Campo magnético desplazado","Calentamiento polar"]},
      neptune:{name:"Neptuno",latin:"NEPTUNUS · GIGANTE HELADO",lead:"El gran planeta más lejano: un mundo oscuro y frío con los vientos más rápidos del Sistema Solar.",story:"Neptuno fue predicho matemáticamente antes de observarse. El metano absorbe la luz roja y otro componente de neblina puede intensificar su azul profundo.",stats:[["Diámetro","49 244 km"],["Año","164,8 años"],["Vientos","hasta 2 100 km/h"],["Lunas conocidas","14+"]],hotspots:["Gran Mancha Oscura","Nubes scooter","Sobrevuelo de Voyager 2"]}
    }
  };

  Object.assign(de.ui, {
    relativeNote:"Der Maßstab basiert auf AE; der innere Bereich ist leicht erweitert, damit die Planeten nicht mit der Sonne verschmelzen.",
    hintOrbit:"<span>LMT</span> drehen <span>KLICK</span> erkunden",
    hintOrbitLocked:"<span>KLICK</span> erkunden", hintOrbitNoExplore:"<span>LMT</span> drehen <span>PLANETEN GESPERRT</span>", hintLockedNoExplore:"<span>PLANETEN GESPERRT</span>", hintLineupNoExplore:"<span>FESTER SCHNITT</span> · <span>PLANETEN GESPERRT</span>", rotationOn:"DREHUNG: AN", rotationOff:"DREHUNG: AUS", rotationToggle:"Drehung mit der linken Maustaste ein- oder ausschalten", rotationDisabled:"LMT-DREHUNG DEAKTIVIERT", explorationOn:"PLANETEN: OFFEN", explorationOff:"PLANETEN: GESPERRT", explorationToggle:"Öffnen von Planeten und Sonne per Klick erlauben oder sperren"
  });
  Object.assign(es.ui, {
    relativeNote:"La escala se basa en UA; la zona interior está ligeramente ampliada para separar los planetas del Sol.",
    hintOrbit:"<span>BOTÓN IZQ.</span> girar <span>CLIC</span> explorar",
    hintOrbitLocked:"<span>CLIC</span> explorar", hintOrbitNoExplore:"<span>BOTÓN IZQ.</span> girar <span>PLANETAS BLOQUEADOS</span>", hintLockedNoExplore:"<span>PLANETAS BLOQUEADOS</span>", hintLineupNoExplore:"<span>CORTE FIJO</span> · <span>PLANETAS BLOQUEADOS</span>", rotationOn:"ROTACIÓN: SÍ", rotationOff:"ROTACIÓN: NO", rotationToggle:"Activar o desactivar el giro con el botón izquierdo", rotationDisabled:"GIRO IZQUIERDO DESACTIVADO", explorationOn:"PLANETAS: SÍ", explorationOff:"PLANETAS: NO", explorationToggle:"Permitir o bloquear la apertura de planetas y el Sol al hacer clic"
  });
  en.orbiterNames = shared.orbiterNames;
  de.orbiterNames = {
    earth:["Mond","ISS","Hubble"], mars:["Phobos","Deimos","MRO"], jupiter:["Io","Europa","Ganymed","Kallisto","Juno"],
    saturn:["Enceladus","Rhea","Titan","Cassini"], uranus:["Miranda","Ariel","Titania","Oberon"], neptune:["Proteus","Triton","Nereide"]
  };
  es.orbiterNames = {
    earth:["Luna","EEI","Hubble"], mars:["Fobos","Deimos","MRO"], jupiter:["Ío","Europa","Ganímedes","Calisto","Juno"],
    saturn:["Encélado","Rea","Titán","Cassini"], uranus:["Miranda","Ariel","Titania","Oberón"], neptune:["Proteo","Tritón","Nereida"]
  };

  window.HELIOS_I18N = { locales:{ ru, en, de, es }, shared };
})();
